//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBGFinance
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.Label lblAvatar;
        protected global::System.Web.UI.WebControls.Label lblAdSoyad;
        protected global::System.Web.UI.WebControls.Label lblRol;
        protected global::System.Web.UI.WebControls.LinkButton lnkCikis;
        protected global::System.Web.UI.WebControls.Panel pnlBreadcrumb;
        protected global::System.Web.UI.WebControls.Panel pnlAdminMenu;
        protected global::System.Web.UI.WebControls.Panel pnlMusteriMenu;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphTitle;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphHead;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphBreadcrumb;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphPageTitle;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphPageSubtitle;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphPageActions;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphScripts;
    }
}
