//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBGFinance.Modules.Rezervasyonlar.Musteri
{
    public partial class Liste
    {
    }
}
